config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  put '/tasks/:id/mark_complete', to: 'tasks#mark_complete', as: 'mark_as_complete' 
  put '/tasks/:id/mark_incomplete', to: 'tasks#mark_incomplete', as: 'mark_as_incomplete' 
end

app/models/task.rb
class Task < ActiveRecord::Base

	# validates :name,:desc,:start,:end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@tasks = Task.all.order(end: :asc)
	end

	def new
		@task = Task.new
	end

	def create
		@task = Task.new(task_params)
		@task.status = false
		@task.save
		respond_to do |format|
			format.html{redirect_to tasks_path}
			format.js{}
		end
	end

	def show
		@task = Task.find(params[:id])
	end

	def edit
		@task = Task.find(params[:id])
	end

	def update
		@task = Task.find(params[:id])
		@task.update(task_params)
		respond_to do |format|
			format.html{redirect_to task_path}
			format.js{}
		end
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		respond_to do |format|
			format.html{redirect_to tasks_path}
			format.js{}
		end
	end

	def mark_complete
		@task = Task.find(params[:id])
		@task.status = true
		@task.save
		respond_to do |format|
			format.html{redirect_to :back}
			format.js{}
		end
	end

	def mark_incomplete
		@task = Task.find(params[:id])
		@task.status = false
		@task.save
		respond_to do |format|
			format.html{redirect_to :back}
			format.js{}
		end
	end

	private
		def task_params
			params.require(:task).permit(:name,:desc,:start,:end)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Todo",tasks_path, class: 'navbar-brand' %>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li><%= link_to "Create", new_task_path %></li>
			<li><%= link_to "Tasks", tasks_path %></li>
		</ul>
	</div>
</nav>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
	<%= f.input :name,input_html:{placeholder: 'Name of task'} %>
	<%= f.input :desc,input_html:{placeholder: 'Description about task'} %>
	<%= f.input :start %>
	<%= f.input :end %>
	<%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/tasks/_task.html.erb
<div class="task">
	<div class="row">
		<div class="col-md-8">
			<h4><%= link_to task.name,task_path(task.id) %></h4>
		</div>
		<div class="col-md-4">
			<% if task.status? %>
				<%= link_to fa_icon('check-circle',text: 'Completed'),mark_as_incomplete_path(task.id),class: 'label label-success pull-right',method: :put  %>
			<% else %>
				<% if Time.now > task.end %>
					<%= link_to fa_icon('check',text: 'Mark as complete'),mark_as_complete_path(task.id),class: 'label label-danger pull-right',method: :put %>
				<% else %>
					<%= link_to fa_icon('check',text: 'Mark as complete'),mark_as_complete_path(task.id),class: 'label label-default pull-right',method: :put %>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<span><label>Start Date:- </label> <%= task.start %></span>
		</div>
		<div class="col-md-6">
			<span><label>Due Date:- </label> <%= task.end %></span>
		</div>
	</div>
</div>

app/views/tasks/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h3>
			Edit Task Details
		</h3>
		<hr/>
		<%= render partial: 'form' %>
	</div>
</div>

app/views/tasks/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="filter-bar row">
			<div class="col-xs-4">
				<%= link_to "All",'#' %>
			</div>
			<div class="col-xs-4">
				<%= link_to "Completed",'#' %>
			</div>
			<div class="col-xs-4">
				<%= link_to "Incomplete",'#' %>
			</div>
		</div>
		<%= render partial: 'task',collection: @tasks %>
	</div>
</div>

app/views/tasks/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h3>Create new task</h3>
		<hr/>
		<%= render partial: 'form' %>
	</div>
</div>

app/views/tasks/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="task">
			<div class="row">
				<div class="col-xs-8">
					<h3><%= @task.name %></h3>
				</div>
				<div class="col-xs-4">
					<% if @task.status? %>
						<%= link_to fa_icon('check-circle',text: 'Completed'),mark_as_incomplete_path(@task.id),class: 'label label-success pull-right',method: :put  %>
					<% else %>
						<% if Time.now > @task.end %>
							<%= link_to fa_icon('check',text: 'Mark as complete'),mark_as_complete_path(@task.id),class: 'label label-danger pull-right',method: :put %>
						<% else %>
							<%= link_to fa_icon('check',text: 'Mark as complete'),mark_as_complete_path(@task.id),class: 'label label-default pull-right',method: :put %>
						<% end %>
					<% end %>
				</div>
			</div>
			<hr>
			<label>Description:</label>
			<p>
				 <%= @task.desc %>
			</p>
			<hr/>
			<div class="row">
				<div class="col-xs-6">
					<p>
					<label>Start Date:</label>
					<%= @task.start %>
					</p>
				</div>
				<div class="col-xs-6">
					<p>
					<label>End Date:</label>
					<%= @task.end %>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>